from __future__ import annotations

from typing import Protocol, runtime_checkable

from PySide6.QtWidgets import QWidget


@runtime_checkable
class MainWindowFacade(Protocol):
    """Narrow interface used by main-window controllers."""

    def translation_input_text(self) -> str: ...

    def translation_clear_input(self) -> None: ...

    def translation_set_input_text(self, text: str) -> None: ...

    def translation_focus_input(self) -> None: ...

    def translation_current_direction(self) -> str: ...

    def translation_current_profile_id(self) -> str: ...

    def translation_current_tag(self) -> str: ...

    def translation_model_index(self) -> int: ...

    def translation_model_count(self) -> int: ...

    def translation_set_model_index(self, index: int) -> None: ...

    def translation_set_direction(self, direction_id: str) -> None: ...

    def translation_refresh_profile_combo(self) -> None: ...

    def translation_set_profile_id(self, profile_id: str) -> None: ...

    def translation_set_status(self, key: str, *, error: bool, **params: object) -> None: ...

    def translation_set_busy(self, busy: bool) -> None: ...

    def translation_show_result(self, result: str, direction: str, profile_id: str) -> None: ...

    def translation_set_output_plain(self, text: str) -> None: ...

    def translation_show_retry(self, visible: bool) -> None: ...

    def translation_reload_tag_combo(self) -> None: ...

    def set_sync_action_enabled(self, enabled: bool) -> None: ...

    def as_qwidget(self) -> QWidget: ...
